//Counter
export enum INCREMENT_COUNT { VAL = 'INCREMENT_COUNT' }
export enum DECREMENT_COUNT { VAL = 'DECREMENT_COUNT' }
//Weather
export enum REQUEST_WEATHER_FORECASTS { VAL = 'REQUEST_WEATHER_FORECASTS' }
export enum RECEIVE_WEATHER_FORECASTS { VAL = 'RECEIVE_WEATHER_FORECASTS' }
//payment Type
export enum REQUEST_TRACKING_NUMBERS { VAL = 'REQUEST_TRACKING_NUMBERS' }
export enum RECEIVE_TRACKING_NUMBERS { VAL = 'RECEIVE_TRACKING_NUMBERS' }
export enum REQUEST_TRACKING_NUMBER { VAL = 'REQUEST_TRACKING_NUMBER' }
export enum RECEIVE_TRACKING_NUMBER { VAL = 'RECEIVE_TRACKING_NUMBER' }

